version: '3.4'

services:
  computearchlinuximagebuilder:
    image: computearchlinuximagebuilder
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m build-arch-grc "]
    ports:
      - 5678:5678
